name: Simulation CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        container: gableroux/unity3d:2020.1.13f1
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                lfs: true

            - name: Run tests
              uses: webbertakken/unity-test-runner@v1.3
              with:
                unityVersion: 2020.1.13f1

            # Build
            - name: Build project
              uses: webbertakken/unity-builder@v0.10
              with:
                unityVersion: 2020.1.13f1
                targetPlatform: Windows

            # Output
            - uses: actions/upload-artifact@v1
              with:
                name: Build
                path: build